# Generated by Django 4.2.2 on 2023-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('body', models.TextField()),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
            ],
        ),
    ]
