# Generated by Django 4.2.2 on 2023-06-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_plants_new_price_alter_plants_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
            ],
        ),
    ]
